### PR TITLE
refactor(native): unify ieee_components for float, double and long double (#1334)

### PR DESCRIPTION
**Pull request by Ravenwater**
## Summary

`ieee754_float.hpp`, `ieee754_double.hpp` and the per-compiler long-double headers are named like core headers and included by nearly everything, but their contents are almost entirely **text**:

| | |
|---|---|
| `to_hex`, `to_binary`, `to_triple`, `to_base2_scientific`, `color_print` | text |
| `ieee_components` | core |

Carrying the text there put `<sstream>` and `<iomanip>` into the include graph of every TU that merely *decodes* a native float. **That is where the four I/O-family headers in every number system's graph come from** — not from the number systems, and not from `blocktriple`, both of which were only passing them along.

## The change: move the minority, for all three real types

```
ieee754_components.hpp   17,885 lines   0 I/O-family    <- new
```

covering **float, double and long double** across the gcc, clang, MSVC and RISC-V compiler branches. The text headers keep their text and lose the one core function each carried; they now include the components header, so **anyone who included them directly and called `ieee_components()` is unaffected** — that is what keeps the blast radius at zero. There are 18 call sites, including `internal/value/value.hpp`.

`ieee754_type_tag.hpp` also gained `<string>` and `<type_traits>`, which it uses and was getting transitively from `<sstream>`.

## The failure mode worth recording

`ieee754_components.hpp` needed `utility/architecture.hpp`. The `long_double_decoder` unions in `ieee754_decoder.hpp` are gated on `UNIVERSAL_ARCH_POWER` / `_X86_64` / `_ARM` / `_RISCV` — without `architecture.hpp` none of those macros are defined, no branch fires, and the decoder is invisible:

```
g++                     'long_double_decoder' was not declared in this scope
riscv64-linux-gnu-g++   'long_double_decoder' was not declared in this scope
clang++                 COMPILED
```

**clang passed while the other two failed**, because its branch reaches a different decoder — the same one-toolchain-passes trap that broke the RISC-V cross build in #1386. `long_double.hpp` and `bit_cast.hpp` are included alongside for the same reason.

## Checked and deliberately not fixed

`ieee754_longdouble.hpp` does not compile standalone: its per-compiler headers use `std::stringstream` without including `<sstream>`. Verified against an `origin/main` worktree — **it does not compile there either**, so this is pre-existing, not a regression. Same class as the 148 headers in #1389, and it only bites a TU that includes that header directly.

## Why this shape, and not blocktriple

An earlier attempt split `blocktriple`'s text layer instead. Measured, it was worth **0.3%** — 100,023 to 99,706 lines, with four I/O-family headers before *and* after — because `native/` supplies all four regardless of what `blocktriple` does. It would also have cost **294 TUs** their includes. Measuring before landing is what redirected the work here.

## The pattern, for whoever extends this

**Move the minority, not the majority.** These headers had 5-6 text functions and 1 core function each. Splitting the file would be churn; lifting the one core function out is a three-line change with zero blast radius, because the original then includes the new header.

1. Classify by return type — `std::string` or a stream parameter means text
2. Lift the core minority into a new header
3. Have the original include it
4. Verify by compiling, never by grepping

**Never lift a region spanning a preprocessor boundary.** A first attempt at these files took an `#endif` along with the text and left an orphaned `#ifdef DEPRECATED`. Lifts now assert the moved block contains no `#if`/`#else`/`#endif`, and `#if`-vs-`#endif` counts are checked after every edit — they balance in all four touched files here.

## Test Results

| check | result |
|---|---|
| `ieee_components` float/double/**long double** | compiles on gcc 13.3, clang 18.1, riscv64 cross |
| runtime values from the light header alone | `1.5f` -> `(0, 127, 0x400000)`, `1.5` -> `(0, 1023, 0x8000000000000)`, `1.5L` -> `(0, 16383, 0x4000000000000000)` |
| 1057-TU sweep, ten source trees | **17 failures, identical to the `main` baseline** — zero regressions |
| preprocessor balance, 4 touched files | open/`#endif` counts match |
| CI_LITE build + `ctest -j4` | **456/456 passed** |
| `check-ascii.sh` | clean |
| added lines over 120 columns | 0 |

## Test plan

- [ ] Fast CI passes
- [ ] CodeRabbit review

Relates to #1334

Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **New Features**
  * Added support for extracting sign, exponent, and fraction components from native single-, double-, and long-double-precision values across supported compiler architectures.
  * Added validation for compatible IEC 559 representations and expected data sizes.
* **Refactor**
  * Consolidated floating-point component handling into a shared interface for consistent behavior.
  * Standardized long-double processing, including support for compiler-specific representations and double-equivalent values.

### CODE REVIEW

File: include/sw/universal/native/ieee754_components.hpp [hunk 1]
```diff
@@ -0,0 +1,178 @@
...
+	double_decoder dd{ fp }; // initializes the first member of the union
+	// Reading inactive union parts is forbidden in constexpr :-(
+	return std::make_tuple<bool, int, std::uint64_t>(
+		static_cast<bool>(dd.parts.sign), 
+		static_cast<int>(dd.parts.exponent),
+		static_cast<std::uint64_t>(dd.parts.fraction) 
+	);
+}
+
+#if (defined(__GNUC__) || defined(__GNUG__)) && !defined(__clang__)
```
[the remark this answers is not in the document]
Comment (Ravenwater) [reply include/sw/universal/native/ieee754_components.hpp:63]: Verified with the cross-toolchain rather than reasoned about, and you are right that the GNU branch wins on RISC-V:

```
$ echo | riscv64-linux-gnu-g++ -dM -E - | grep -E '__riscv|__GNUC__|__LDBL_MANT_DIG__'
#define __riscv 1
#define __GNUC__ 13
#define __LDBL_MANT_DIG__ 113        <- binary128
```

Both macros are defined, the GNU test is first, so `#elif defined(__riscv)` is unreachable there.

**But the root cause is one level down, and it is pre-existing.** `ieee754_decoder.hpp` gives RISC-V an x87-shaped `long_double_decoder` and says so in a comment: *"how does RISC-V model its long double? for the moment, just use the x86 interpretation"* -- a 63-bit fraction plus explicit integer bit, for a type that is binary128. So even dispatching RISC-V to its own branch would decode through the wrong union.

**This PR neither introduces nor worsens it.** `nonconstexpr/gcc_long_double.hpp` on `main` carries the identical `(__GNUC__ || __GNUG__) && !__clang__` guard, so the GNU implementation has always been the one selected on RISC-V; this PR moves that code verbatim. And `ieee754_decoder.hpp` is untouched by the diff.

Filed as #1399 with the toolchain evidence, the dispatch-order question, and a note that `ieee_components` returning `std::uint64_t` cannot carry a 112-bit fraction anyway -- so fixing it is a signature change, not just a layout one. Also recorded why it went unnoticed: CI cross-compiles RISC-V but does not run the binaries, and the union type-checks because its fields have the right *names*.

File: include/sw/universal/native/ieee754_components.hpp [hunk 2]
```diff
@@ -0,0 +1,178 @@
...
+			"This function only works when double complies with IEC 559 (IEEE 754)");
+
+        double_decoder decoder;
+        decoder.d = number; // implicit cast to double
+		// Reading inactive union parts is forbidden in constexpr :-(
+		return std::make_tuple<bool, int, std::uint64_t>(
+			static_cast<bool>(decoder.parts.sign),
+			static_cast<int>(decoder.parts.exponent),
+			static_cast<std::uint64_t>(decoder.parts.fraction)
+		);
```
[the remark this answers is not in the document]
Comment (Ravenwater) [reply include/sw/universal/native/ieee754_components.hpp:151]: Also pre-existing, and I checked rather than assumed. `main`'s `nonconstexpr/clang_long_double.hpp` has the identical structure -- `#if UNIVERSAL_ARCH_POWER ... #else ... #if __LDBL_MANT_DIG__ == 113 ... #else` -- with the `double_decoder` fallback at line 553, which is exactly the code this PR moved to `ieee754_components.hpp`. Same nesting, same fallback, same loss of the extended-precision bits on an x87 clang target.

So the concern is real but it is not a regression: this PR relocates the implementations without changing which one a given target selects.

Grouping it with #1399 rather than fixing it here, for the reason that governs the rest of this epic: the value of a move is that it is behaviour-preserving, and changing what the moved code does undercuts the one property that makes the diff reviewable. #1399 covers the long-double decoding layer as a whole -- the RISC-V union, the dispatch order, and the fact that the `std::uint64_t` fraction cannot represent binary128 regardless of which branch is selected.

File: include/sw/universal/native/ieee754_components.hpp [hunk 3]
```diff
@@ -0,0 +1,178 @@
...
+	//////////////////////////////////////////////////////////////////////////////////////////
+	///        long double == double (e.g. Apple Clang on macOS aarch64)
+
+	// ieee_components returns a tuple of sign, exponent, and fraction
+	inline std::tuple<bool, int, std::uint64_t> ieee_components(long double number)	{
+		static_assert(std::numeric_limits<long double>::is_iec559,
+			"This function only works when double complies with IEC 559 (IEEE 754)");
+
+        double_decoder decoder;
+        decoder.d = number; // implicit cast to double
```
[the remark this answers is not in the document]
Comment (Ravenwater) [reply include/sw/universal/native/ieee754_components.hpp]: Fixed. Two lines in the clang fallback used four-space indentation where the project uses tabs; they came across with the moved code. `ieee754_components.hpp` is now 79 tab-indented lines and 0 space-indented, so the new file is internally consistent.

Worth noting the file is new, which is why I took this one rather than leaving it: elsewhere in this epic I have declined range-only reformatting of existing space-indented headers, since it would introduce mixed indentation rather than remove it. Here there is no such tension.
